Helper Reference Manual for linux-generic: odph_list_internal.h File Reference
odph_list_internal.h File Reference
ODP list a simple implementation of Doubly linked list.
Data Structures
struct odph_list_object
List object.
Macros
#define container_of(ptr, type, list_node) ((type *)(void *)((char *)ptr - offsetof(type, list_node)))
#define ODPH_LIST_FOR_EACH(pos, list_head, type, list_node)
Typedefs
typedef struct odph_list_object odph_list_object
List object.
typedef odph_list_object odph_list_head
Head of list.
Functions
static void ODPH_INIT_LIST_HEAD (odph_list_object *list)
static void __odph_list_add (odph_list_object *new, odph_list_object *prev, odph_list_object *next)
static void odph_list_add (odph_list_object *new, odph_list_object *head)
static void odph_list_add_tail (struct odph_list_object *new, odph_list_object *head)
static void __odph_list_del (struct odph_list_object *prev, odph_list_object *next)
static void odph_list_del (struct odph_list_object *entry)
static int odph_list_empty (const struct odph_list_object *head)
Detailed Description
ODP list a simple implementation of Doubly linked list.
Definition in file odph_list_internal.h.
Macro Definition Documentation
container_of
#define container_of (ptr, type, list_node) ((type *)(void *)((char *)ptr - offsetof(type, list_node)))
Definition at line 90 of file odph_list_internal.h.
ODPH_LIST_FOR_EACH
#define ODPH_LIST_FOR_EACH (pos, list_head, type, list_node)
Value:
for (pos = container_of((list_head)->next, type, list_node); \
        &pos->list_node != (list_head); \
        pos = container_of(pos->list_node.next, type, list_node))
Definition at line 94 of file odph_list_internal.h.
Function Documentation
ODPH_INIT_LIST_HEAD()
static void ODPH_INIT_LIST_HEAD (odph_list_object * list) inline static
Intiailize list head element
Parameters
list List object to be initialized
Definition at line 38 of file odph_list_internal.h.
References odph_list_object::next, and odph_list_object::prev.
Referenced by odph_list_del().
__odph_list_add()
static void __odph_list_add (odph_list_object * new, odph_list_object * prev, odph_list_object * next) inline static
Inline function
Parameters
new
prev
next
Definition at line 45 of file odph_list_internal.h.
References odph_list_object::next, and odph_list_object::prev.
Referenced by odph_list_add(), and odph_list_add_tail().
odph_list_add()
static void odph_list_add (odph_list_object * new, odph_list_object * head) inline static
Inline function
Parameters
new
head
Definition at line 56 of file odph_list_internal.h.
References __odph_list_add(), and odph_list_object::next.
odph_list_add_tail()
static void odph_list_add_tail (struct odph_list_object * new, odph_list_object * head) inline static
Inline function
Parameters
new
head
Definition at line 62 of file odph_list_internal.h.
References __odph_list_add(), and odph_list_object::prev.
__odph_list_del()
static void __odph_list_del (struct odph_list_object * prev, odph_list_object * next) inline static
Inline function
Parameters
prev
next
Definition at line 69 of file odph_list_internal.h.
References odph_list_object::next, and odph_list_object::prev.
Referenced by odph_list_del().
odph_list_del()
static void odph_list_del (struct odph_list_object * entry) inline static
Inline function
Parameters
entry
Definition at line 77 of file odph_list_internal.h.
References __odph_list_del(), odph_list_object::next, ODPH_INIT_LIST_HEAD(), and odph_list_object::prev.
odph_list_empty()
static int odph_list_empty (const struct odph_list_object * head) inline static
Inline function
Parameters
head
Returns
Definition at line 84 of file odph_list_internal.h.
References odph_list_object::next.